[package]
name = "termagotchi"
version = "0.1.0"
authors = ["Trevor Arjeski <tmarjeski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"